name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up mise
      uses: jdx/mise-action@v2
      with:
        version: 2025.1.17
        install: true
        cache: true

    - name: Set up environment
      run: mise install

    - name: Install just and GLFW3
      run: |
        sudo apt-get update
        sudo apt-get install -y just libglfw3-dev

    - name: Run just recipes
      run: |
        just build
        just test
